### ISSUE TITLE
Source view feature (selecting node and pressing <i> key) needs fixing

### ISSUE THREAD

**Issue by WillAdams** [KennedyRichard/nodezator#10]
(after updating to 1.0.12)

If you place and select that node:

![image](https://user-images.githubusercontent.com/3543154/174934670-e57e3716-4536-41b8-ba64-f1d7bfbc007f.png)

tapping i w/ it selected crashes the app.

(same thing happens w/ append_to_text_file)

**Comment by KennedyRichard** [comment]
Just uploaded the new version to https://pypi.org

Execute `pip3 install --upgrade nodezator` to upgrade to version 1.0.13.

That's all.
