### ISSUE TITLE
Where would you like discussion to take place?

### ISSUE THREAD

**Issue by WillAdams** [KennedyRichard/nodezator#2]
A number of folks have posted in the Reddit thread:

https://old.reddit.com/r/Python/comments/vf6h1z/nodezator_new_python_node_editor_released_to/

would you want to enable discussions here on GitHub? 

https://docs.github.com/en/discussions/quickstart

It would make sharing images and files easier.

**Comment by KennedyRichard** [comment]
It will be my pleasure, I didn't know such convenient centralized spaced existed. Here in my timezone is lunch time. I'll be back in a couple of hours and enable the discussions.
