### ISSUE TITLE
X'ing out a data source which is connected closes the app

### ISSUE THREAD

**Issue by WillAdams** [KennedyRichard/nodezator#3]
Given a graph:

![image](https://user-images.githubusercontent.com/3543154/174487129-9c78158f-1043-4109-96e0-78b34abe036d.png)

(attached)

[test.zip](https://github.com/KennedyRichard/nodezator/files/8935749/test.zip)

clicking on a red x to remove the value of the data source results in an immediate closing of the app.

**Comment by KennedyRichard** [comment]
I was able to find and fix the bug and already patched it. Please, update to 1.0.7 and try again, and, if it all works fine, let me know so I can close the issue.

**Comment by WillAdams** [comment]
Yes, confirmed as fixed in 1.0.7. Thanks!
