### ISSUE TITLE
Exported python graphs give warning on Windows

### ISSUE THREAD

**Issue by Starbuck5** [KennedyRichard/nodezator#5]
When opening an exported as python graph with IDLE on Windows, I get:

```
Mixed newlines detected.
The file will be changed on save.
```

I see in graphman/pythonrepr that you use os.linesep almost everywhere, but you missed one normal newline: https://github.com/KennedyRichard/nodezator/blob/master/nodezator/graphman/pythonrepr.py#L157

However, I believe I believe it would be more correct to change out all your use of os.linesep for normal newlines.

[See the os.linesep documentation:](https://docs.python.org/3/library/os.html#os.linesep)
> Do not use os.linesep as a line terminator when writing files opened in text mode (the default); use a single '\n' instead, on all platforms.

I also found this handy stackoverflow post that explained it to me: https://stackoverflow.com/questions/38074811/what-is-os-linesep-for.

**Comment by KennedyRichard** [comment]
All needed changes were made. Nodezator 1.0.12 release candidate now uses regular '\n' characters instead of os.linesep on nodezator/graphman/pythonrepr.py. Thank you again for opening the issue and sharing your knowledge! :relieved:

**Comment by KennedyRichard** [comment]
Additionally, os.linesep is used in other modules as well, but their usage in such spots do not produce warnings or anything of the kind.

Even so, I'll include an item called "review usage of os.linesep throughout nodezator" when I list changes to be scheduled for one of the next versions in the discussion I said I'd open on the github discussions for nodezator. That's all for now.
